### ISSUE TITLE
Comparisons Visuals misalignment between compile points, cycles, and slider

### ISSUE THREAD

**Issue by nelsonni** [MichaelHilton/TDDStudy#33]
If you look at the screenshot I included, it shows that both the first and last compile have significantly smaller width than all of the other compiles. This is causing the alignment of the researcher marked cycles and compile border lines to be off from the compilation numbers.

![screenshot from 2015-01-07 21 19 41](https://cloud.githubusercontent.com/assets/6432572/5658242/5bff99c6-96b3-11e4-9ee7-9610a9f6c4eb.png)

**Comment by MichaelHilton** [comment]
Sorry, the comparison view is all messed up, I’m looking at it now.  Also it is not drawing things right.

I’ll let you know as soon as I clean it up.

Michael Hilton
